import { Priority, Status, Task } from './types';

export const PHASES = [
  'Requirements',
  'Software Requirements Specification (SRS)',
  'UI/UX Design',
  'Database Design',
  'Backend Development',
  'Frontend Development',
  'User Testing',
  'Software Testing (QA)',
  'Deployment',
  'Post-Deployment Monitoring',
];

export const STATUSES: Status[] = ['To Do', 'In Progress', 'Completed', 'Blocked'];
export const PRIORITIES: Priority[] = ['High', 'Medium', 'Low'];

export const INITIAL_TASKS: Task[] = [
  {
    id: '1',
    name: 'User Authentication API',
    description: 'Develop endpoints for user registration, login, and logout.',
    assignedTo: 'John Doe',
    priority: 'High',
    estimatedHours: 24,
    startDate: new Date('2024-07-01'),
    endDate: new Date('2024-07-10'),
    status: 'In Progress',
    percentComplete: 60,
    dependencies: 'DB Schema Completion',
    phase: 'Backend Development',
    notes: 'Using JWT for authentication tokens.',
    subTasks: [
      { id: 'sub-1-1', name: 'Create user model', completed: true },
      { id: 'sub-1-2', name: 'Implement /register endpoint', completed: true },
      { id: 'sub-1-3', name: 'Implement /login endpoint', completed: false },
      { id: 'sub-1-4', name: 'Implement /logout endpoint', completed: false },
    ]
  },
  {
    id: '2',
    name: 'Design Landing Page Mockup',
    description: 'Create high-fidelity mockups for the main landing page in Figma.',
    assignedTo: 'Jane Smith',
    priority: 'Medium',
    estimatedHours: 16,
    startDate: new Date('2024-06-25'),
    endDate: new Date('2024-07-05'),
    status: 'Completed',
    percentComplete: 100,
    phase: 'UI/UX Design',
  },
  {
    id: '3',
    name: 'Define Project Scope',
    description: 'Outline the key features and deliverables for the first release.',
    assignedTo: 'Alice Johnson',
    priority: 'High',
    estimatedHours: 8,
    startDate: new Date('2024-06-20'),
    endDate: new Date('2024-06-22'),
    status: 'Completed',
    percentComplete: 100,
    phase: 'Requirements',
    subTasks: [
      { id: 'sub-3-1', name: 'Draft initial feature list', completed: true },
      { id: 'sub-3-2', name: 'Review with stakeholders', completed: true },
      { id: 'sub-3-3', name: 'Finalize V1 scope document', completed: true },
    ]
  },
    {
    id: '4',
    name: 'Setup CI/CD Pipeline',
    description: 'Configure continuous integration and deployment pipeline.',
    assignedTo: 'Charlie Brown',
    priority: 'High',
    estimatedHours: 20,
    startDate: new Date('2024-08-01'),
    endDate: new Date('2024-08-07'),
    status: 'To Do',
    percentComplete: 0,
    phase: 'Deployment',
  },
  {
    id: '5',
    name: 'Write User Stories',
    description: 'Document user stories for all core features.',
    assignedTo: 'Alice Johnson',
    priority: 'Medium',
    estimatedHours: 12,
    startDate: new Date('2024-06-23'),
    endDate: new Date('2024-06-28'),
    status: 'Completed',
    percentComplete: 100,
    phase: 'Software Requirements Specification (SRS)',
  },
  {
    id: '6',
    name: 'API Endpoint Testing',
    description: 'Write and execute integration tests for all backend APIs.',
    assignedTo: 'Grace Hopper',
    priority: 'Medium',
    estimatedHours: 30,
    startDate: new Date('2024-07-11'),
    endDate: new Date('2024-07-20'),
    status: 'Blocked',
    percentComplete: 25,
    dependencies: 'User Authentication API',
    phase: 'Software Testing (QA)',
  },
];
